CREATE TABLE coaches
(
    id      BIGSERIAL PRIMARY KEY ,
    name    VARCHAR(255) NOT NULL
);

CREATE TABLE leagues
(
    id   BIGSERIAL PRIMARY KEY ,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE matches
(
    id           BIGSERIAL PRIMARY KEY ,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    league_id    BIGINT NOT NULL
);

CREATE TABLE players
(
    id      BIGSERIAL PRIMARY KEY ,
    name    VARCHAR(255) NOT NULL,
    team_id BIGINT
);

CREATE TABLE players_statistics
(
    id          BIGSERIAL PRIMARY KEY,
    player_id   BIGINT NOT NULL,
    kills       INTEGER NOT NULL DEFAULT 0,
    deaths      INTEGER NOT NULL DEFAULT 0,
    assists     INTEGER NOT NULL DEFAULT 0,
    wins        INTEGER NOT NULL DEFAULT 0,
    losses      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE teams
(
    id        BIGSERIAL PRIMARY KEY ,
    name      VARCHAR(255) NOT NULL,
    league_id BIGINT,
    coach_id BIGINT UNIQUE
);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_AWAY_TEAM FOREIGN KEY (away_team_id) REFERENCES teams (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_HOME_TEAM FOREIGN KEY (home_team_id) REFERENCES teams (id);

ALTER TABLE matches
    ADD CONSTRAINT FK_MATCHES_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (id);

ALTER TABLE players
    ADD CONSTRAINT FK_PLAYERS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE SET NULL;

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (id) ON DELETE SET NULL;

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_COACH FOREIGN KEY (coach_id) REFERENCES coaches (id) ON DELETE SET NULL;

ALTER TABLE players_statistics
    ADD CONSTRAINT FK_PLAYERS_ON_STATISTICS FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE SET NULL;